line-length = 80

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]
"w_parser/settings.py" = ["E", "C90"]
"**/migrations/*.py" = ["ALL"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]