# Generated by Django 5.2.3 on 2025-07-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='WB ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (₽)')),
                ('discount_price', models.PositiveIntegerField(verbose_name='Цена со скидкой (₽)')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('reviews', models.PositiveIntegerField(verbose_name='Число отзывов')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
            ],
            options={
                'verbose_name': 'Поиск',
                'verbose_name_plural': 'Поиски',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_parser.product', verbose_name='Товар')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w_parser.search', verbose_name='Поиск')),
            ],
            options={
                'verbose_name': 'Связь Поиск–Товар',
                'verbose_name_plural': 'Связи Поиск–Товар',
                'unique_together': {('search', 'product')},
            },
        ),
        migrations.AddField(
            model_name='search',
            name='products',
            field=models.ManyToManyField(related_name='searches', through='w_parser.SearchProduct', to='w_parser.product', verbose_name='Товары'),
        ),
    ]
