# Generated by Django 5.2.3 on 2025-07-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (₽)')),
                ('discount_price', models.PositiveIntegerField(verbose_name='Цена со скидкой (₽)')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('reviews', models.PositiveIntegerField(verbose_name='Число отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
